### PR TITLE
adding preliminary renv stuff

### PR DESCRIPTION
**Pull request by nickreich**

### CODE REVIEW

**Comment by bsweger** [comment]
Love a good virtual environment--thanks!

**Comment by elray1** [comment]
Is the idea that this virtual environment will be used by package developers?  Is it standard practice to ship dev environments as part of packages?  What are best practices for sharing environments?

**Comment by nickreich** [comment]
Per conversation with @bsweger we are thinking that we should add all the renv stuff to .Rbuildignore and .gitignore so people can use these on their own, but the feeling is that renv should not be forced upon folks for this project.

**Comment by bsweger** [comment]
For posterity, here's the internal Slack thread where some of us talked about this (and apologies to @annakrystalli for not respecting the "have all convos on github" philosophy: https://reichlab.slack.com/archives/C01AN0JE46R/p1705589000904249

**Comment by bsweger** [comment]
Closing this as part of some cleanup!

**Pull request closed without merging**
